# Generated by Django 5.0.6 on 2024-05-19 12:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    run_before = [
        ("admin", "0001_initial"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("num_code", models.CharField(max_length=3)),
                ("sym_code", models.CharField(max_length=5)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "rate_type",
                    models.CharField(choices=[("sell", "Sell"), ("buy", "Buy"), ("cross", "Cross")], max_length=5),
                ),
                ("date", models.DateField()),
                (
                    "currency1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="from_rates", to="currencies.currency"
                    ),
                ),
                (
                    "currency2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="to_rates", to="currencies.currency"
                    ),
                ),
            ],
        ),
    ]
